Increment 5
zavtra-na-rabotu/gometrics pull request #5
Opened 2024-05-06 21:10 UTC by zavtra-na-rabotu

2024-05-12 18:11 UTC, avhitrov requested changes
1. Неверное поведение счетчика
2. Утечки в процедуре отправки данных агента
3. DATA RACE на сервере
4. Мелкие замечания в комментариях к коду.

2024-05-12 18:11 UTC, avhitrov commented on internal/agent/metrics/sender.go
> +	_, err := client.R().Post(url)
```suggestion
	resp, err := client.R().Post(url)
```

2024-05-12 18:11 UTC, avhitrov commented on internal/agent/metrics/sender.go
> +	}
После блока еще необходимо добавить закрытие тела, чтобы избежать утечек.
```
resp.Body.Close()

return nil
```

2024-05-12 18:11 UTC, avhitrov commented on internal/agent/metrics/sender.go
> +		log.Printf("Failed to send metric %s: %v", metricName, err)
```
return err
```

2024-05-12 18:11 UTC, avhitrov commented on internal/agent/metrics/sender.go
> +func sendMetric[T int64 | float64](client *resty.Client, metricType internal.MetricType, metricName string, value T) {
```suggestion
func sendMetric[T int64 | float64](client *resty.Client, metricType internal.MetricType, metricName string, value T) error {
```

2024-05-12 18:11 UTC, avhitrov commented on internal/metrictype.go
Правильнее будет создать внутри `internal` папку `models` и туда сложить общие константы и описание типов, общие для агента и сервера. И все описания структур протокола взаимодействия.

2024-05-12 18:11 UTC, avhitrov commented on internal/server/storage/memstorage.go
> +	return storage.gauge
После снятия блокировки мапа, возвращенная данной функцией (То же и для `GetAllCounter`) становится беззащитной. Последующая работа с ней приводит к возникновению гонок.

См. https://t.me/bushigo/24 (Третья иллюзия)

```
==================
WARNING: DATA RACE
Write at 0x00c000088f00 by goroutine 2631:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  github.com/zavtra-na-rabotu/gometrics/internal/server/storage.(*MemStorage).UpdateGauge()
      C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/storage/memstorage.go:30 +0xe4
  main.main.UpdateMetric.func1()
      C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/handlers/handlers.go:116 +0x29b
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Previous read at 0x00c000088f00 by goroutine 2639:
  runtime.mapiterinit()
      C:/Apps/Go/src/runtime/map.go:816 +0x0
  main.main.RenderAllMetrics.func3()
      C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/handlers/handlers.go:136 +0x109
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Goroutine 2631 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x5e4
  main.main()
      C:/work/src/github.com/zavtra-na-rabotu/gometrics/cmd/server/main.go:22 +0x4db

Goroutine 2639 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x5e4
  main.main()
      C:/work/src/github.com/zavtra-na-rabotu/gometrics/cmd/server/main.go:22 +0x4db
==================
```

2024-05-12 20:16 UTC, zavtra-na-rabotu commented on internal/agent/metrics/sender.go
> +	}
Если я правильно понял, в случае с resty, он все сделает сам, если не используется [https://pkg.go.dev/github.com/go-resty/resty/v2#Client.SetDoNotParseResponse](SetDoNotParseResponse)

2024-05-15 21:11 UTC, avhitrov commented on internal/agent/metrics/sender.go
> +	}
Да, так и есть. Забыл про данную особенность либы.

2024-05-15 21:19 UTC, avhitrov approved these changes
Все замечания исправлены. Отлично!

2024-05-15 21:19 UTC, avhitrov commented on internal/server/handlers/handlers.go
> +// GetMetric TODO: What to do if variable name and package name are the same ? Only aliases ?
Это разруливается в go, используя некоторые умолчания, приоритеты и синтаксический сахар. Но лучше не допускать совпадения названий переменных и пакетов. Иначе самому легко запутаться.

2024-05-18 15:07 UTC, merged