Increment 9
zavtra-na-rabotu/gometrics pull request #9
Opened 2024-05-28 16:11 UTC by zavtra-na-rabotu

2024-06-03 20:56 UTC, avhitrov requested changes
В соответствии с заданием, если выставить в качестве имени файла пустую строку, должен произвестись откат на работу в памяти. В текущей реализации, если запустить сервер `.\server.exe -a :8080 -f=""`, то он сразу упадет:
```
2024-06-03T23:53:32.301+0300    ERROR   storage/filestorage.go:113      Failed to create new reader     {"error": "error opening file: open : The system cannot find the file specified."}
github.com/zavtra-na-rabotu/gometrics/internal/server/storage.RestoreMetricsFromFile
        C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/storage/filestorage.go:113
main.main
        C:/work/src/github.com/zavtra-na-rabotu/gometrics/cmd/server/main.go:36
runtime.main
        C:/Apps/Go/src/runtime/proc.go:271
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1405a779b]

goroutine 1 [running]:
github.com/zavtra-na-rabotu/gometrics/internal/server/storage.(*Reader).Close(...)
        C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/storage/filestorage.go:76
github.com/zavtra-na-rabotu/gometrics/internal/server/storage.RestoreMetricsFromFile.func1()
        C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/storage/filestorage.go:108 +0x3b
github.com/zavtra-na-rabotu/gometrics/internal/server/storage.RestoreMetricsFromFile(0xc00011e7c0, {0xc00011c0fe, 0x0})
        C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/storage/filestorage.go:114 +0x2ec
main.main()
        C:/work/src/github.com/zavtra-na-rabotu/gometrics/cmd/server/main.go:36 +0x90e
```

2024-06-04 18:14 UTC, zavtra-na-rabotu commented
> В соответствии с заданием, если выставить в качестве имени файла пустую строку, должен произвестись откат на работу в памяти. В текущей реализации, если запустить сервер `.\server.exe -a :8080 -f=""`, то он сразу упадет:
> 
> ```
> 2024-06-03T23:53:32.301+0300    ERROR   storage/filestorage.go:113      Failed to create new reader     {"error": "error opening file: open : The system cannot find the file specified."}
> github.com/zavtra-na-rabotu/gometrics/internal/server/storage.RestoreMetricsFromFile
>         C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/storage/filestorage.go:113
> main.main
>         C:/work/src/github.com/zavtra-na-rabotu/gometrics/cmd/server/main.go:36
> runtime.main
>         C:/Apps/Go/src/runtime/proc.go:271
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x0 pc=0x1405a779b]
> 
> goroutine 1 [running]:
> github.com/zavtra-na-rabotu/gometrics/internal/server/storage.(*Reader).Close(...)
>         C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/storage/filestorage.go:76
> github.com/zavtra-na-rabotu/gometrics/internal/server/storage.RestoreMetricsFromFile.func1()
>         C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/storage/filestorage.go:108 +0x3b
> github.com/zavtra-na-rabotu/gometrics/internal/server/storage.RestoreMetricsFromFile(0xc00011e7c0, {0xc00011c0fe, 0x0})
>         C:/work/src/github.com/zavtra-na-rabotu/gometrics/internal/server/storage/filestorage.go:114 +0x2ec
> main.main()
>         C:/work/src/github.com/zavtra-na-rabotu/gometrics/cmd/server/main.go:36 +0x90e
> ```

Исправил, также заметил что забыл про синхронную запись при storeInterval == 0 (тоже доделал)

2024-06-08 21:59 UTC, avhitrov approved these changes
Все отлично!

2024-06-08 21:59 UTC, avhitrov commented on cmd/server/config.go
> +	if exists {
👍

2024-06-09 16:37 UTC, merged